server:
  port: 8080

file:
  #静态资源对外的访问路径
  virtualPath: /files/**
  #实际的访问路径
  realPath: E:\Idea\Idea_project\ai_edu\ai_edu_server\src\main\java\com\coder_mart_server\filesStore\

spring:
  servlet:
    multipart:
      #单个文件最大大小
      max-file-size: 20MB
      #一个HTTP请求最大允许大小（多文件上传最大容量）
      max-request-size: 100MB
  profiles:
    active: dev

  # 数据库配置
  datasource:
    driver-class-name: ${my-config.datasource.driver-class-name}
    url: jdbc:mysql://${my-config.datasource.host}:${my-config.datasource.port}/${my-config.datasource.database}
    username: ${my-config.datasource.username}
    password: ${my-config.datasource.password}

  # redis配置
  redis:
    host: ${my-config.redis.host}
    port: ${my-config.redis.port}
    database: ${my-config.redis.database}


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/**/*.xml